/* Pushing electrons: molecule data.
   Each entry gives the first structure and the arrows; engine.js derives the rest.
   See README.md for the format. */

function ring(pre, n, start, labels = {}) {
  const R = BL / (2*Math.sin(Math.PI/n));
  const atoms = {}, bonds = [];
  for (let i = 0; i < n; i++) {
    const t = (start + 360*i/n) * R2D;
    atoms[pre+i] = [R*Math.cos(t), R*Math.sin(t), labels[i] || ''];
    bonds.push(`${pre}${i}-${pre}${(i+1)%n}@${pre}`);
  }
  return {atoms, bonds: bonds.join(' '), centers: {[pre]: {x:0, y:0}}};
}

function annulene(n, sign) {
  const R = ring('r', n, -90);
  const d = [];
  for (let j = 1; j+1 < n; j += 2) d.push(`r${j}-r${j+1}`);
  const steps = [];
  let k = 0;
  for (let s = 0; s < n; s++) {
    const a = k, b = (k+1)%n, c = (k+2)%n;
    steps.push(sign < 0 ? `r${a}>r${a}-r${b} r${b}-r${c}>r${c}` : `r${b}-r${c}>r${a}-r${b}`);
    k = c;
  }
  return {atoms: R.atoms, bonds: R.bonds, centers: R.centers, d: d.join(' '), q: {r0: sign}, steps};
}

const K1 = 'c0-c1 c2-c3 c4-c5';
const KSHIFT = 'c0-c5>c0-c1 c1-c2>c2-c3 c3-c4>c4-c5';
const donorSteps = D => [`${D}>${D}-c0 c0-c1>c1`, 'c1>c1-c2 c2-c3>c3', 'c3>c3-c4 c4-c5>c5', `c5>c0-c5 ${D}-c0>${D}`, KSHIFT];
const accSteps = (X, Y) => [`c0-c1>c0-${X}` + (Y ? ` ${X}-${Y}>${Y}` : ''), 'c2-c3>c1-c2', 'c4-c5>c3-c4', (Y ? `${Y}>${X}-${Y} ` : '') + `c0-${X}>c0-c5`, KSHIFT];

function benz(extraAtoms, extraBonds, rest) {
  const R = ring('c', 6, -90);
  return Object.assign({atoms: Object.assign({}, R.atoms, extraAtoms), bonds: R.bonds + ' ' + extraBonds, centers: R.centers, d: K1 + (rest.d ? ' ' + rest.d : '')}, rest, {d: K1 + (rest.d ? ' ' + rest.d : '')});
}

/* ---------- the molecules ---------- */
const EX = [
/* ===== Allylic & conjugated ===== */
{n:'Allyl cation', c:'Allylic & conjugated', b:'A + charge that moves',
 i:'A positive carbon sits next to a C=C. The π electrons slide over to fill the empty orbital, so the + isn\u2019t stuck on one end.',
 h:'Each end carries about half a + charge, and both C\u2013C bonds are 1\u00BD bonds. Spreading the charge is why allylic cations form so easily (think SN1 at allylic positions).',
 atoms:{a:[0,0,'H2C'],b:['a',30,''],c:['b',-30,'CH2']}, bonds:'a-b b-c', d:'a-b', q:{c:1}, steps:['a-b>b-c']},
{n:'Allyl anion', c:'Allylic & conjugated', b:'A lone pair next to a π bond',
 i:'A carbanion next to a C=C. The lone pair can become a π bond, pushing the old π electrons to the far end.',
 h:'The negative charge is shared by both ends; the middle carbon never carries it. That spacing (ends only) is the signature of allylic systems.',
 atoms:{a:[0,0,'H2C'],b:['a',30,''],c:['b',-30,'CH2']}, bonds:'a-b b-c', d:'a-b', q:{c:-1}, steps:['c>b-c a-b>a']},
{n:'Pentadienyl cation', c:'Allylic & conjugated', b:'Charge on every other carbon',
 i:'Two C=C bonds conjugated with a carbocation. The + hops two carbons at a time.',
 h:'The + is spread over C1, C3 and C5, never on C2 or C4. More conjugation means more delocalization and a more stable cation.',
 atoms:{a:[0,0,'H2C'],b:['a',30,''],c:['b',-30,''],d2:['c',30,''],e:['d2',-30,'CH2']}, bonds:'a-b b-c c-d2 d2-e', d:'b-c d2-e', q:{a:1},
 steps:['b-c>a-b','d2-e>c-d2','c-d2>d2-e a-b>b-c']},
{n:'1,3-Butadiene', c:'Allylic & conjugated', b:'Why the middle bond is short',
 i:'No charges to start with. Pushing electrons creates a charge-separated structure, a small but real contributor.',
 h:'The C2\u2013C3 bond has a little double-bond character, so it\u2019s shorter than a normal single bond (1.47 vs 1.54 \u00C5). That\u2019s the conjugation you\u2019ll see in UV spectra and Diels\u2013Alder reactions.',
 atoms:{a:[0,0,'H2C'],b:['a',30,''],c:['b',-30,''],d2:['c',30,'CH2']}, bonds:'a-b b-c c-d2', d:'a-b c-d2', steps:['a-b>b-c c-d2>d2']},
{n:'Propargyl cation', c:'Allylic & conjugated', b:'A triple bond shares the charge',
 i:'A carbocation next to a C\u2261C. One of the triple bond\u2019s π bonds can move over, giving an allene-type cation.',
 h:'The + is split between the CH\u2082 end and the far CH end. The same kind of resonance explains how propargyl and allenyl products interconvert.',
 atoms:{a:[0,0,'HC'],b:['a',0,'C'],c:['b',0,'CH2']}, bonds:'a-b b-c', t:'a-b', q:{c:1}, steps:['a-b>b-c']},

/* ===== Carbocations ===== */
{n:'Oxocarbenium ion', c:'Cations', b:'Oxygen rescues a carbocation',
 i:'A carbocation next to an oxygen. The oxygen\u2019s lone pair fills the empty orbital.',
 h:'The O=C form is major because every atom has an octet, even though the + ends up on oxygen. These ions show up in acetal formation and sugar chemistry.',
 atoms:{a:[0,0,'H2C'],o:['a',30,'O'],m:['o',-30,'CH3']}, bonds:'a-o o-m', d:'a-o', q:{o:1}, steps:['a-o>o']},
{n:'Iminium ion', c:'Cations', b:'Nitrogen does it even better',
 i:'Nitrogen is a better lone-pair donor than oxygen, so iminium ions are quite stable.',
 h:'Mostly C=N\u207A with some carbocation character at carbon. That carbon is where nucleophiles attack (reductive amination, Mannich reaction).',
 atoms:{a:[0,0,'H2C'],n:['a',30,'N'],m1:['n',-30,'CH3'],m2:['n',90,'CH3']}, bonds:'a-n n-m1 n-m2', d:'a-n', q:{n:1}, steps:['a-n>n']},
{n:'Acylium ion', c:'Cations', b:'The Friedel\u2013Crafts electrophile',
 i:'The acylium ion from Friedel\u2013Crafts acylation. The triple-bonded form looks odd but has octets everywhere.',
 h:'The C\u2261O\u207A form dominates, which is why acylium ions don\u2019t rearrange like ordinary carbocations. The electrophile is still the carbon.',
 atoms:{m:[0,0,'H3C'],c:['m',0,'C'],o:['c',0,'O']}, bonds:'m-c c-o', t:'c-o', q:{o:1}, steps:['c-o>o']},
{n:'Protonated ketone', c:'Cations', b:'Why acid activates C=O',
 i:'Adding H\u207A to a carbonyl oxygen. Push the C=O π bond onto oxygen and a carbocation appears.',
 h:'The minor carbocation form shows why acid catalysis works: protonation makes the carbonyl carbon much more electrophilic.',
 atoms:{m1:[0,0,'H3C'],c:['m1',-30,'C'],m2:['c',30,'CH3'],o:['c',-90,'OH']}, bonds:'m1-c c-m2 c-o', d:'c-o', q:{o:1}, steps:['c-o>o']},
{n:'Diazonium ion', c:'Cations', b:'N\u2261N\u207A and its minor partner',
 i:'Diazonium ions are famous leaving groups. The minor contributor puts the + on the terminal nitrogen.',
 h:'Mostly N\u2261N\u207A. Losing N\u2082 gas is so favorable that diazonium ions are great for making aryl halides, phenols and azo dyes.',
 atoms:{m:[0,0,'H3C'],n1:['m',0,'N'],n2:['n1',0,'N']}, bonds:'m-n1 n1-n2', t:'n1-n2', q:{n1:1}, steps:['n1-n2>n1']},

/* ===== Carbonyl groups ===== */
{n:'Ketone C=O', c:'Carbonyl groups', b:'The polarized carbonyl',
 i:'Acetone. Even a neutral carbonyl has a charge-separated contributor.',
 h:'The C=O is polarized: \u03B4+ carbon, \u03B4\u2212 oxygen. That\u2019s why nucleophiles attack the carbon of every carbonyl.',
 atoms:{m1:[0,0,'H3C'],c:['m1',-30,'C'],m2:['c',30,'CH3'],o:['c',-90,'O']}, bonds:'m1-c c-m2 c-o', d:'c-o', steps:['c-o>o']},
{n:'Carboxylate', c:'Carbonyl groups', b:'Why carboxylic acids are acidic',
 i:'Acetate, formed when acetic acid loses H\u207A. Where does the negative charge go?',
 h:'Both C\u2013O bonds are identical (about 1.26 \u00C5) and each oxygen holds half the charge. That stabilization makes carboxylic acids about 10\u00B9\u00B9 times more acidic than alcohols.',
 atoms:{m:[0,0,'H3C'],c:['m',-30,'C'],o1:['c',-90,'O'],o2:['c',30,'O']}, bonds:'m-c c-o1 c-o2', d:'c-o1', q:{o2:-1}, steps:['o2>c-o2 c-o1>o1']},
{n:'Carboxylic acid', c:'Carbonyl groups', b:'OH donates into C=O',
 i:'The OH oxygen can donate a lone pair into the carbonyl, even before the proton leaves.',
 h:'A small contribution, but it lowers the carbonyl\u2019s reactivity compared with a ketone.',
 atoms:{m:[0,0,'H3C'],c:['m',-30,'C'],o1:['c',-90,'O'],o2:['c',30,'OH']}, bonds:'m-c c-o1 c-o2', d:'c-o1', steps:['o2>c-o2 c-o1>o1']},
{n:'Ester', c:'Carbonyl groups', b:'Less reactive than ketones',
 i:'Methyl acetate. The ether-type oxygen donates into the C=O.',
 h:'The donation makes the carbonyl carbon less electrophilic, which is why esters react more slowly with nucleophiles than aldehydes or ketones.',
 atoms:{m:[0,0,'H3C'],c:['m',-30,'C'],o1:['c',-90,'O'],o2:['c',30,'O'],m2:['o2',-30,'CH3']}, bonds:'m-c c-o1 c-o2 o2-m2', d:'c-o1', steps:['o2>c-o2 c-o1>o1']},
{n:'Amide', c:'Carbonyl groups', b:'The lone pair that isn\u2019t free',
 i:'Nitrogen is a strong donor, so an amide\u2019s lone pair is pulled well into the carbonyl.',
 h:'The C\u2013N bond has partial double-bond character. Amides are flat, the C\u2013N bond doesn\u2019t rotate freely, and amide nitrogens are barely basic. This is why proteins have rigid peptide bonds.',
 atoms:{m:[0,0,'H3C'],c:['m',-30,'C'],o:['c',-90,'O'],n:['c',30,'NH2']}, bonds:'m-c c-o c-n', d:'c-o', steps:['n>c-n c-o>o']},
{n:'Acid chloride', c:'Carbonyl groups', b:'A donor that barely donates',
 i:'Chlorine has lone pairs, but its large 3p orbitals overlap poorly with carbon\u2019s 2p.',
 h:'The Cl\u207A contributor is very minor. Little donation plus a great leaving group makes acid chlorides the most reactive carboxylic acid derivatives.',
 atoms:{m:[0,0,'H3C'],c:['m',-30,'C'],o:['c',-90,'O'],cl:['c',30,'Cl']}, bonds:'m-c c-o c-cl', d:'c-o', steps:['cl>c-cl c-o>o']},
{n:'Enone', c:'Carbonyl groups', b:'The Michael acceptor',
 i:'A C=C conjugated with C=O. The carbonyl pulls electrons all the way from the far carbon.',
 h:'The \u03B2-carbon (end of the C=C) is \u03B4+. That\u2019s why soft nucleophiles add there in conjugate (Michael) additions.',
 atoms:{m:[0,0,'H3C'],c:['m',-30,'C'],o:['c',-90,'O'],ca:['c',30,''],cb:['ca',-30,'CH2']}, bonds:'m-c c-o c-ca ca-cb', d:'c-o ca-cb', steps:['c-o>o ca-cb>c-ca']},
{n:'Enaminone', c:'Carbonyl groups', b:'Push meets pull',
 i:'A donor (N) and an acceptor (C=O) at opposite ends of a C=C. Electrons flow all the way across.',
 h:'Strong push\u2013pull makes the C=C partly single and the C=O partly single. These \u201Cvinylogous amides\u201D behave a lot like amides.',
 atoms:{n:[0,0,'N'],nm1:['n',210,'H3C'],nm2:['n',90,'CH3'],ca:['n',-30,''],cb:['ca',30,''],c:['cb',-30,'C'],o:['c',-90,'O'],m:['c',30,'CH3']},
 bonds:'n-nm1 n-nm2 n-ca ca-cb cb-c c-o c-m', d:'ca-cb c-o', steps:['n>n-ca ca-cb>cb-c c-o>o']},
{n:'Urea', c:'Carbonyl groups', b:'Two nitrogens take turns',
 i:'Either nitrogen can donate into the carbonyl, giving two equivalent charge-separated contributors.',
 h:'Both C\u2013N bonds have partial double-bond character and the oxygen is quite electron-rich, which makes urea a strong hydrogen-bond acceptor.',
 atoms:{c:[0,0,'C'],o:['c',-90,'O'],n1:['c',150,'H2N'],n2:['c',30,'NH2']}, bonds:'c-o c-n1 c-n2', d:'c-o',
 steps:['n1>c-n1 c-o>o','n2>c-n2 c-n1>n1','o>c-o c-n2>n2']},
{n:'Carbonate ion', c:'Carbonyl groups', b:'Three oxygens, one double bond',
 i:'Three oxygens share one π bond and two negative charges.',
 h:'All three C\u2013O bonds are identical (1\u2153 bonds) and each oxygen carries \u2154 of a negative charge.',
 atoms:{c:[0,0,'C'],o1:['c',-90,'O'],o2:['c',150,'O'],o3:['c',30,'O']}, bonds:'c-o1 c-o2 c-o3', d:'c-o1', q:{o2:-1,o3:-1},
 steps:['o2>c-o2 c-o1>o1','o3>c-o3 c-o2>o2','o1>c-o1 c-o3>o3']},
{n:'Guanidinium ion', c:'Carbonyl groups', b:'The arginine side chain',
 i:'Three nitrogens around one carbon share a + charge. This is the side chain of arginine.',
 h:'The + is spread over all three nitrogens, which makes guanidine one of the strongest neutral organic bases (conjugate acid pKa \u2248 13.6).',
 atoms:{c:[0,0,'C'],n1:['c',-90,'NH2'],n2:['c',150,'H2N'],n3:['c',30,'NH2']}, bonds:'c-n1 c-n2 c-n3', d:'c-n1', q:{n1:1},
 steps:['n2>c-n2 c-n1>n1','n3>c-n3 c-n2>n2','n1>c-n1 c-n3>n3']},
{n:'Ketene', c:'Carbonyl groups', b:'A carbonyl with a C=C attached',
 i:'Ketenes have two cumulated double bonds. Pushing electrons reveals a nucleophilic carbon.',
 h:'The terminal CH\u2082 carbon is \u03B4\u2212 and the central carbon is very electrophilic. That\u2019s why ketenes react fast with water, alcohols and amines.',
 atoms:{a:[0,0,'H2C'],c:['a',0,'C'],o:['c',0,'O']}, bonds:'a-c c-o', d:'a-c c-o', steps:['o>c-o a-c>a']},

/* ===== Enolates & donors on C=C ===== */
{n:'Enolate', c:'Enolates & donors', b:'One ion, two reactive sites',
 i:'Remove a proton next to a C=O and you get an enolate. The negative charge is shared by oxygen and carbon.',
 h:'Charge mostly on O, some on C. Enolates can react at either atom; with most carbon electrophiles, they react at carbon (aldol, alkylation).',
 atoms:{o:[0,0,'O'],c:['o',30,'C'],m:['c',90,'CH3'],a:['c',-30,'CH2']}, bonds:'o-c c-m c-a', d:'c-a', q:{o:-1}, steps:['o>o-c c-a>a']},
{n:'Enol', c:'Enolates & donors', b:'A neutral nucleophile',
 i:'The enol form of acetone. The OH oxygen pushes electrons onto carbon.',
 h:'The \u03B1-carbon of an enol is electron-rich, so enols act as carbon nucleophiles in acid-catalyzed \u03B1-halogenation and aldol reactions.',
 atoms:{o:[0,0,'HO'],c:['o',30,'C'],m:['c',90,'CH3'],a:['c',-30,'CH2']}, bonds:'o-c c-m c-a', d:'c-a', steps:['o>o-c c-a>a']},
{n:'Enamine', c:'Enolates & donors', b:'The Stork enamine',
 i:'Nitrogen is a better donor than oxygen, so enamines are more nucleophilic at carbon than enols.',
 h:'The \u03B2-carbon is \u03B4\u2212. Enamines alkylate at carbon (Stork enamine synthesis) and give iminium ions that hydrolyze back to ketones.',
 atoms:{n:[0,0,'N'],m1:['n',150,'H3C'],m2:['n',-90,'CH3'],c:['n',30,''],a:['c',-30,'CH2']}, bonds:'n-m1 n-m2 n-c c-a', d:'c-a', steps:['n>n-c c-a>a']},
{n:'Enol ether', c:'Enolates & donors', b:'An electron-rich alkene',
 i:'Methyl vinyl ether. The oxygen makes the C=C electron-rich.',
 h:'The terminal carbon is \u03B4\u2212, so electrophiles (like H\u207A) add there, making an oxocarbenium ion.',
 atoms:{m:[0,0,'H3C'],o:['m',30,'O'],c:['o',-30,''],a:['c',30,'CH2']}, bonds:'m-o o-c c-a', d:'c-a', steps:['o>o-c c-a>a']},
{n:'Vinyl chloride', c:'Enolates & donors', b:'A halogen as a weak donor',
 i:'Chlorine can donate a lone pair into a C=C, though weakly.',
 h:'The C\u2013Cl bond gains a little double-bond character, making vinyl halides much less reactive in SN1 and SN2 than alkyl halides.',
 atoms:{cl:[0,0,'Cl'],c:['cl',-30,''],a:['c',30,'CH2']}, bonds:'cl-c c-a', d:'c-a', steps:['cl>cl-c c-a>a']},
{n:'Acrylonitrile', c:'Enolates & donors', b:'A nitrile pulls from a C=C',
 i:'A C=C conjugated with a C\u2261N. The nitrogen can take a lone pair, leaving the far carbon positive.',
 h:'The terminal CH\u2082 is \u03B4+, so acrylonitrile is a good Michael acceptor and polymerizes readily.',
 atoms:{a:[0,0,'H2C'],c:['a',-30,''],cn:['c',30,'C'],n:['cn',30,'N']}, bonds:'a-c c-cn cn-n', d:'a-c', t:'cn-n', steps:['cn-n>n a-c>c-cn']},
{n:'Acetylacetonate', c:'Enolates & donors', b:'Charge over five atoms',
 i:'The enolate of a 1,3-diketone. The charge can sit on the central carbon or either oxygen.',
 h:'Spread over O, C and O. This extra delocalization makes 1,3-dicarbonyl C\u2013H bonds unusually acidic (pKa \u2248 9 vs about 19 for acetone).',
 atoms:{m1:[0,0,'H3C'],c1:['m1',-30,'C'],o1:['c1',-90,'O'],c2:['c1',30,''],c3:['c2',-30,'C'],o2:['c3',-90,'O'],m2:['c3',30,'CH3']},
 bonds:'m1-c1 c1-o1 c1-c2 c2-c3 c3-o2 c3-m2', d:'c1-o1 c3-o2', q:{c2:-1},
 steps:['c2>c1-c2 c1-o1>o1','o1>c1-o1 c1-c2>c2-c3 c3-o2>o2','o2>c3-o2 c2-c3>c2']},
{n:'Dienolate', c:'Enolates & donors', b:'An extended enolate',
 i:'An enolate with an extra C=C. The charge can travel down the chain to the far (\u03B3) carbon.',
 h:'Charge on O, the \u03B1-carbon and the \u03B3-carbon. Dienolates can react at either carbon, which gives chemists a way to functionalize the \u03B3 position.',
 atoms:{o:[0,0,'O'],c1:['o',30,'C'],m:['c1',90,'CH3'],c2:['c1',-30,''],c3:['c2',30,''],c4:['c3',-30,'CH2']},
 bonds:'o-c1 c1-m c1-c2 c2-c3 c3-c4', d:'c1-c2 c3-c4', q:{o:-1},
 steps:['o>o-c1 c1-c2>c2','c2>c2-c3 c3-c4>c4','c4>c3-c4 c2-c3>c1-c2 c1-o>o']},
{n:'Nitronate', c:'Enolates & donors', b:'The enolate of a nitro compound',
 i:'Nitroalkanes are surprisingly acidic. Deprotonation gives a nitronate ion.',
 h:'Charge is shared by the oxygens and the carbon. Nitronates act as carbon nucleophiles in the Henry (nitroaldol) reaction.',
 atoms:{a:[0,0,'H2C'],n:['a',30,'N'],o1:['n',-30,'O'],o2:['n',90,'O']}, bonds:'a-n n-o1 n-o2', d:'a-n', q:{n:1,o1:-1,o2:-1}, steps:['o1>n-o1 a-n>a']},

/* ===== Small molecules & ions ===== */
{n:'Nitro group', c:'Small molecules & ions', b:'Two equal N\u2013O bonds',
 i:'Nitromethane. Nitrogen carries a permanent +, and the \u2212 is shared by the two oxygens.',
 h:'The N\u2013O bonds are identical (1\u00BD bonds). The nitro group is strongly electron-withdrawing.',
 atoms:{m:[0,0,'H3C'],n:['m',0,'N'],o1:['n',-60,'O'],o2:['n',60,'O']}, bonds:'m-n n-o1 n-o2', d:'n-o1', q:{n:1,o2:-1}, steps:['o2>n-o2 n-o1>o1']},
{n:'Nitrate ion', c:'Small molecules & ions', b:'Three equivalent oxygens',
 i:'The nitrate ion, NO\u2083\u207B. Same pattern as carbonate, with nitrogen in the middle.',
 h:'All three N\u2013O bonds are identical (1\u2153 bonds), each oxygen carrying \u2154 of a negative charge.',
 atoms:{n:[0,0,'N'],o1:['n',-90,'O'],o2:['n',150,'O'],o3:['n',30,'O']}, bonds:'n-o1 n-o2 n-o3', d:'n-o1', q:{n:1,o2:-1,o3:-1},
 steps:['o2>n-o2 n-o1>o1','o3>n-o3 n-o2>o2','o1>n-o1 n-o3>o3']},
{n:'Nitrite ion', c:'Small molecules & ions', b:'Bent, with a lone pair on N',
 i:'NO\u2082\u207B. Two oxygens share one π bond and one negative charge.',
 h:'Both N\u2013O bonds are the same length, and the ion is bent because nitrogen keeps a lone pair.',
 atoms:{n:[0,0,'N'],o1:['n',150,'O'],o2:['n',30,'O']}, bonds:'n-o1 n-o2', d:'n-o1', q:{o2:-1}, steps:['o2>n-o2 n-o1>o1']},
{n:'Ozone', c:'Small molecules & ions', b:'Resonance in a pure element',
 i:'O\u2083. Even with only oxygen atoms, formal charges appear in every octet structure.',
 h:'Both O\u2013O bonds are identical (1.28 \u00C5, between O\u2013O and O=O). The central oxygen is \u03B4+ and the ends are \u03B4\u2212.',
 atoms:{o2:[0,0,'O'],o1:['o2',150,'O'],o3:['o2',30,'O']}, bonds:'o1-o2 o2-o3', d:'o1-o2', q:{o2:1,o3:-1}, steps:['o3>o2-o3 o1-o2>o1']},
{n:'Azide ion', c:'Small molecules & ions', b:'A linear N\u2083\u207B',
 i:'Azide is linear. The symmetric form is best; moving charge to one end creates a 2\u2212 nitrogen.',
 h:'Mostly the symmetric N=N=N form, with both ends \u03B4\u2212. The terminal nitrogens are nucleophilic (SN2 with alkyl halides, click chemistry).',
 atoms:{n1:[0,0,'N'],n2:['n1',0,'N'],n3:['n2',0,'N']}, bonds:'n1-n2 n2-n3', d:'n1-n2 n2-n3', q:{n1:-1,n2:1,n3:-1}, steps:['n1>n1-n2 n2-n3>n3']},
{n:'Diazomethane', c:'Small molecules & ions', b:'Nucleophilic carbon, great leaving group',
 i:'CH\u2082N\u2082. The minor contributor puts a negative charge on carbon next to N\u2261N.',
 h:'The carbon is \u03B4\u2212 and basic. It grabs a proton from a carboxylic acid, then N\u2082 leaves, making methyl esters.',
 atoms:{a:[0,0,'H2C'],n1:['a',0,'N'],n2:['n1',0,'N']}, bonds:'a-n1 n1-n2', d:'a-n1 n1-n2', q:{n1:1,n2:-1}, steps:['n2>n1-n2 a-n1>a']},
{n:'Nitrous oxide', c:'Small molecules & ions', b:'Laughing gas',
 i:'N\u2082O is linear, with the oxygen on one end. Two octet structures contribute.',
 h:'Both contributors matter. The N\u2013N bond is between double and triple, and the N\u2013O bond is between single and double.',
 atoms:{n1:[0,0,'N'],n2:['n1',0,'N'],o:['n2',0,'O']}, bonds:'n1-n2 n2-o', t:'n1-n2', q:{n2:1,o:-1}, steps:['o>n2-o n1-n2>n1']},
{n:'Carbon monoxide', c:'Small molecules & ions', b:'Octets beat charges',
 i:'CO is best drawn with a triple bond and formal charges, because then both atoms have octets.',
 h:'Mostly C\u2261O. The lone pair on carbon is why CO binds metals through carbon (and binds hemoglobin so dangerously well).',
 atoms:{c:[0,0,'C'],o:['c',0,'O']}, bonds:'c-o', t:'c-o', q:{c:-1,o:1}, steps:['c-o>o']},
{n:'Carbon dioxide', c:'Small molecules & ions', b:'Hidden polarity',
 i:'CO\u2082 has no net dipole, but its bonds are polar. The minor contributors show it.',
 h:'The carbon is \u03B4+ and electrophilic, which is how CO\u2082 reacts with Grignard reagents to make carboxylic acids. A mirror-image contributor puts the charges the other way.',
 atoms:{o1:[0,0,'O'],c:['o1',0,'C'],o2:['c',0,'O']}, bonds:'o1-c c-o2', d:'o1-c c-o2', steps:['c-o1>o1 o2>c-o2']},
{n:'Cyanate ion', c:'Small molecules & ions', b:'Charge on O or N',
 i:'OCN\u207B. The negative charge can sit on oxygen or nitrogen.',
 h:'Both ends are nucleophilic. Reacting at N gives isocyanates; reacting at O gives cyanates.',
 atoms:{o:[0,0,'O'],c:['o',0,'C'],n:['c',0,'N']}, bonds:'o-c c-n', t:'c-n', q:{o:-1}, steps:['o>o-c c-n>n']},
{n:'Thiocyanate ion', c:'Small molecules & ions', b:'Sulfur vs nitrogen',
 i:'SCN\u207B, the sulfur version of cyanate.',
 h:'Charge is shared by S and N. Soft electrophiles tend to bond to sulfur; hard ones to nitrogen.',
 atoms:{s:[0,0,'S'],c:['s',0,'C'],n:['c',0,'N']}, bonds:'s-c c-n', t:'c-n', q:{s:-1}, steps:['s>s-c c-n>n']},
{n:'Nitrile', c:'Small molecules & ions', b:'An electrophilic carbon',
 i:'Acetonitrile. One π bond of the C\u2261N can move onto nitrogen.',
 h:'The nitrile carbon is \u03B4+, so nitriles are attacked by nucleophiles (hydrolysis to acids, Grignard addition to make ketones).',
 atoms:{m:[0,0,'H3C'],c:['m',0,'C'],n:['c',0,'N']}, bonds:'m-c c-n', t:'c-n', steps:['c-n>n']},
{n:'Isocyanide', c:'Small molecules & ions', b:'A carbon with a lone pair',
 i:'Methyl isocyanide. Like CO, the triple-bonded form with charges is best.',
 h:'The terminal carbon has a lone pair and some carbene character. Isocyanides react at carbon with both electrophiles and nucleophiles (Ugi and Passerini reactions).',
 atoms:{m:[0,0,'H3C'],n:['m',0,'N'],c:['n',0,'C']}, bonds:'m-n n-c', t:'n-c', q:{n:1,c:-1}, steps:['n-c>n']},
{n:'Nitrone', c:'Small molecules & ions', b:'A 1,3-dipole',
 i:'Nitrones are 1,3-dipoles: charges can sit on atoms 1 and 3 of a three-atom unit.',
 h:'Negative charge shared by O and C. This lets nitrones do 1,3-dipolar cycloadditions with alkenes.',
 atoms:{a:[0,0,'H2C'],n:['a',30,'N'],m:['n',90,'CH3'],o:['n',-30,'O']}, bonds:'a-n n-m n-o', d:'a-n', q:{n:1,o:-1}, steps:['o>n-o a-n>a']},
{n:'Phosphorus ylide', c:'Small molecules & ions', b:'The Wittig reagent',
 i:'Ph\u2083P=CH\u2082. Phosphorus can exceed an octet, so a P=C form can be drawn, but the ylide form is the better description.',
 h:'Mostly P\u207A\u2013C\u207B, because 3d orbitals barely take part in bonding. The nucleophilic carbon attacks carbonyls in the Wittig reaction.',
 atoms:{p:[0,0,'Ph3P',{el:'P',h:3,a:'end'}],c:['p',0,'CH2']}, bonds:'p-c', q:{p:1,c:-1}, steps:['c>p-c'], tags:'Mm', notes:['Both atoms keep an octet. This ylide picture is the better description.','Phosphorus would need ten electrons here, using d orbitals that barely take part in bonding. Minor contributor.']},

/* ===== Aromatic rings ===== */
(()=>{const R=ring('c',6,-90);return{n:'Benzene', c:'Aromatic rings', b:'Where do the double bonds go?',
 i:'Six carbons and three π bonds, with no single correct place to draw them. All three arrows fire at once.',
 h:'All six C\u2013C bonds are identical (1.39 \u00C5). The six π electrons spread around the whole ring, the root of aromatic stability.',
 atoms:R.atoms, bonds:R.bonds, centers:R.centers, d:K1, steps:['c0-c1>c1-c2 c2-c3>c3-c4 c4-c5>c5-c0']}})(),
(()=>{const R=ring('c',6,-90,{0:'N'});return{n:'Pyridine', c:'Aromatic rings', b:'An electron-poor ring',
 i:'Pyridine is aromatic like benzene. Nitrogen\u2019s extra electronegativity pulls π electrons toward it.',
 h:'The 2, 4 and 6 positions are \u03B4+. Nucleophiles attack there, and electrophilic substitution is slow. The N lone pair points out of the ring and isn\u2019t part of the aromatic system.',
 atoms:R.atoms, bonds:R.bonds, centers:R.centers, d:K1, steps:['c0-c1>c0','c2-c3>c1-c2','c4-c5>c3-c4','c0>c0-c5',KSHIFT]}})(),
...['N','O','S'].map(X=>{const R=ring('r',5,90,{0:X});const nm={N:'Pyrrole',O:'Furan',S:'Thiophene'}[X];
 const atoms=Object.assign({},R.atoms); let bonds=R.bonds; if(X==='N'){atoms.h=['r0',90,'H'];bonds+=' r0-h'}
 return{n:nm, c:'Aromatic rings', b:{N:'The N lone pair joins the ring',O:'An oxygen in an aromatic ring',S:'Sulfur\u2019s 3p lone pair'}[X],
 i:{N:'In pyrrole, the nitrogen\u2019s lone pair is part of the aromatic sextet. Pushing it into the ring puts negative charge on every carbon.',O:'Furan\u2019s oxygen donates one lone pair into the ring; the other stays in the plane.',S:'Thiophene is the most aromatic of the three five-membered heterocycles, because sulfur holds its charge least tightly.'}[X],
 h:{N:'All four carbons are \u03B4\u2212, so pyrrole is very reactive toward electrophiles, mostly at C2. The nitrogen is \u03B4+ and not basic at all.',O:'The ring carbons are \u03B4\u2212, making furan reactive toward electrophiles (at C2) and a good Diels\u2013Alder diene.',S:'The carbons are \u03B4\u2212. Thiophene undergoes electrophilic substitution at C2 like the others, but behaves the most like benzene.'}[X],
 atoms, bonds, centers:R.centers, d:'r1-r2 r3-r4',
 steps:['r0>r0-r1 r1-r2>r2','r2>r2-r3 r3-r4>r4','r4>r0-r4 r0-r1>r1','r1>r1-r2 r2-r3>r3','r3>r3-r4 r0-r4>r0']}}),
Object.assign(annulene(3,1),{n:'Cyclopropenyl cation', c:'Aromatic rings', b:'The smallest aromatic ring',
 i:'Two π electrons in a three-membered ring: aromatic by H\u00FCckel\u2019s rule (4n+2 with n = 0).',
 h:'Each carbon carries \u2153 of the + charge and all three bonds are identical. Despite the strained ring, this cation is surprisingly stable.'}),
Object.assign(annulene(5,-1),{n:'Cyclopentadienyl anion', c:'Aromatic rings', b:'Six π electrons in five atoms',
 i:'Deprotonating cyclopentadiene gives an aromatic anion. The lone pair can move to any carbon.',
 h:'Each carbon carries \u2155 of the charge. Aromaticity makes cyclopentadiene unusually acidic for a hydrocarbon (pKa \u2248 16), and this anion is the ligand in ferrocene.'}),
Object.assign(annulene(7,1),{n:'Tropylium cation', c:'Aromatic rings', b:'Seven carbons, one + charge',
 i:'Six π electrons over seven carbons. The + visits every carbon in turn.',
 h:'Each carbon carries \u2150 of the + charge. Tropylium salts are stable enough to put in a bottle, rare for a carbocation.'}),

/* ===== Substituted benzenes ===== */
benz({X:['c0',-90,'O']},'c0-X',{n:'Phenoxide', c:'Substituted benzenes', b:'Why phenols are acidic',
 i:'Phenol loses H\u207A to give phenoxide. The charge spreads into the ring.',
 h:'The charge is on O and the ortho and para carbons. That stabilization makes phenol a million times more acidic than cyclohexanol (pKa 10 vs 16).',
 q:{X:-1}, steps:donorSteps('X')}),
benz({X:['c0',-90,'OH']},'c0-X',{n:'Phenol', c:'Substituted benzenes', b:'A strong ortho/para director',
 i:'The OH group donates a lone pair into the ring.',
 h:'Ortho and para carbons are \u03B4\u2212. Phenol undergoes electrophilic aromatic substitution much faster than benzene, at ortho and para.',
 steps:donorSteps('X')}),
benz({X:['c0',-90,'NH2']},'c0-X',{n:'Aniline', c:'Substituted benzenes', b:'The most activated ring',
 i:'Nitrogen\u2019s lone pair is pulled into the ring, charging the ortho and para carbons.',
 h:'Ortho and para carbons are \u03B4\u2212, so aniline brominates instantly at all three. The delocalized lone pair also makes aniline a much weaker base than alkylamines.',
 steps:donorSteps('X')}),
benz({X:['c0',-90,'O'],me:['X',-30,'CH3']},'c0-X X-me',{n:'Anisole', c:'Substituted benzenes', b:'Methoxy: an activating group',
 i:'Methoxybenzene. The oxygen donates into the ring even though it\u2019s electronegative.',
 h:'Resonance donation outweighs oxygen\u2019s inductive pull, so OCH\u2083 is activating and directs electrophiles ortho and para.',
 steps:donorSteps('X')}),
benz({X:['c0',-90,'Cl']},'c0-X',{n:'Chlorobenzene', c:'Substituted benzenes', b:'Deactivating, yet ortho/para',
 i:'Chlorine donates a lone pair into the ring, but weakly.',
 h:'Halogens are the classic exception: inductive withdrawal makes the ring less reactive, but resonance still directs electrophiles to ortho and para.',
 steps:donorSteps('X')}),
benz({X:['c0',-90,'CH2']},'c0-X',{n:'Benzyl cation', c:'Substituted benzenes', b:'Why benzylic SN1 is fast',
 i:'A carbocation attached to a benzene ring. The ring\u2019s π electrons flow toward the empty orbital.',
 h:'The + is spread over the CH\u2082 and the ortho and para carbons. Benzylic halides ionize easily in SN1 reactions for this reason.',
 q:{X:1}, steps:accSteps('X')}),
benz({X:['c0',-90,'CH2']},'c0-X',{n:'Benzyl anion', c:'Substituted benzenes', b:'Why benzylic C\u2013H is acidic',
 i:'A carbanion next to a benzene ring. The lone pair spreads into the ring.',
 h:'Charge on CH\u2082 and the ortho and para carbons. That\u2019s why toluene\u2019s CH\u2083 (pKa \u2248 41) is far more acidic than methane\u2019s (\u2248 50).',
 q:{X:-1}, steps:donorSteps('X')}),
benz({X:['c0',-90,'C'],xh:['X',-150,'H'],y:['X',-30,'O']},'c0-X X-xh X-y',{n:'Benzaldehyde', c:'Substituted benzenes', b:'A meta director',
 i:'The carbonyl pulls electrons out of the ring.',
 h:'Ortho and para carbons are \u03B4+, so electrophiles avoid them. The meta position is least deactivated, which makes CHO a meta director.',
 d:'X-y', steps:accSteps('X','y')}),
benz({X:['c0',-90,'N'],y:['X',-150,'O'],z:['X',-30,'O']},'c0-X X-y X-z',{n:'Nitrobenzene', c:'Substituted benzenes', b:'The strongest common deactivator',
 i:'The nitro group pulls π electrons out of the ring onto oxygen.',
 h:'Strong \u03B4+ at ortho and para. Nitrobenzene is very slow in electrophilic substitution and goes meta. For nucleophilic aromatic substitution, it activates ortho and para. (The two N\u2013O bonds are also equivalent, thanks to the nitro group\u2019s own resonance, which isn\u2019t shown here.)',
 d:'X-y', q:{X:1,z:-1}, steps:accSteps('X','y')}),
benz({X:['c0',-90,'C'],y:['X',-90,'N']},'c0-X X-y',{n:'Benzonitrile', c:'Substituted benzenes', b:'A triple bond pulls from the ring',
 i:'One π bond of the C\u2261N accepts electrons from the ring.',
 h:'Ortho and para carbons are \u03B4+, so CN is deactivating and meta-directing.',
 t:'X-y', steps:accSteps('X','y')}),
(()=>{const R=ring('c',6,-90);return{n:'Arenium ion', c:'Substituted benzenes', b:'The EAS intermediate',
 i:'After an electrophile (here Br) adds to benzene, the ring carbon becomes sp\u00B3 and a + appears. This is the sigma complex.',
 h:'The + is spread over the two ortho carbons and the para carbon. Groups that stabilize those positions speed up electrophilic aromatic substitution and direct it there.',
 atoms:Object.assign({},R.atoms,{hx:['c0',-120,'H'],br:['c0',-60,'Br']}), bonds:R.bonds+' c0-hx c0-br', centers:R.centers,
 d:'c2-c3 c4-c5', q:{c1:1}, steps:['c2-c3>c1-c2','c4-c5>c3-c4','c3-c4>c4-c5 c1-c2>c2-c3']}})()
];

